project:
  type: website

website:
  title: "<img src='/images/stock_prices.png' alt='Stock Symbol' style='width: 2.6em; height: 2.2em; border-radius: 30%;'> <b>Big Tech Stock Prices</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
